# Generated by Django 3.0.2 on 2020-01-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('citizenship_no', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('citizenship_scan', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=10)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
        ),
    ]
