# Generated by Django 3.0.2 on 2020-01-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password1',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password2',
            new_name='password',
        ),
    ]
