# Generated by Django 3.0.2 on 2020-01-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='charpani', max_length=20),
        ),
    ]
